// Segundo lote: TODO lo demás de las listas del chat, sin filtrar.
const TOKEN = "certpath-admin-2026";
const c = (name, vendor, domain, level = "associate", cost = "pago") => ({
  name, vendor, domain, level, cost, url: "",
});

const items = [
  // AWS extras
  c("AWS Cloud Operations", "AWS", "cloud"),
  c("AWS Well-Architected", "AWS", "cloud", "fundamentos"),
  c("AWS Migration Specialist", "AWS", "cloud", "specialty"),
  c("AWS Serverless", "AWS", "devops", "professional"),
  c("AWS Generative AI", "AWS", "ia", "specialty"),
  c("AWS Bedrock Specialist", "AWS", "ia", "specialty"),
  c("AWS Data Analytics", "AWS", "ia", "specialty"),
  c("AWS Security Engineer", "AWS", "ciberseguridad", "professional"),
  // Azure extras
  c("Azure Virtual Desktop Specialty", "Microsoft", "cloud", "specialty"),
  c("Azure Kubernetes Service", "Microsoft", "devops", "associate"),
  c("Azure Networking", "Microsoft", "redes", "associate"),
  c("Azure Identity & Access", "Microsoft", "ciberseguridad", "associate"),
  c("Microsoft Sentinel", "Microsoft", "ciberseguridad", "associate"),
  c("Microsoft Defender", "Microsoft", "ciberseguridad", "associate"),
  c("Azure OpenAI", "Microsoft", "ia", "associate"),
  c("Microsoft Fabric Analytics Engineer", "Microsoft", "ia", "associate"),
  c("Microsoft Fabric Data Engineer", "Microsoft", "ia", "associate"),
  c("Microsoft Fabric Architect", "Microsoft", "ia", "expert"),
  c("Power Platform Developer (PL-400)", "Microsoft", "ia", "associate"),
  // GCP extras
  c("Google Workspace Administrator", "Google Cloud", "soporte", "associate"),
  c("Google Cloud Database Engineer", "Google Cloud", "ia", "professional"),
  c("Google Vertex AI Engineer", "Google Cloud", "ia", "professional"),
  c("Google Generative AI Engineer", "Google Cloud", "ia", "professional"),
  // Cisco extras
  c("CCNP Collaboration", "Cisco", "redes", "professional"),
  c("CCNP DevNet", "Cisco", "devops", "professional"),
  c("CCIE Data Center", "Cisco", "redes", "expert"),
  c("Cisco SD-WAN", "Cisco", "redes", "professional"),
  c("Cisco Wireless", "Cisco", "redes", "professional"),
  c("Cisco Meraki Solutions", "Cisco", "redes", "associate"),
  c("Cisco ACI", "Cisco", "redes", "professional"),
  c("Cisco Network Security Specialist", "Cisco", "ciberseguridad", "professional"),
  // Linux extras
  c("LPIC-3 Mixed Environment", "LPI", "linux", "expert"),
  c("LPIC-3 Virtualization", "LPI", "linux", "expert"),
  c("SUSE Certified Administrator", "SUSE", "linux", "associate"),
  c("SUSE Certified Engineer", "SUSE", "linux", "professional"),
  c("Oracle Linux Administrator", "Oracle", "linux", "associate"),
  c("Red Hat OpenShift Architect", "Red Hat", "devops", "expert"),
  // Ciberseguridad extras
  c("CompTIA Network+", "CompTIA", "redes", "associate"),
  c("ISC2 HCISPP", "ISC2", "grc", "professional"),
  c("CRTO (Red Team Operator)", "Zero-Point Security", "ciberseguridad", "professional"),
  c("CRTP (Red Team Professional)", "Altered Security", "ciberseguridad", "professional"),
  c("CARTP (Azure Red Team)", "Altered Security", "ciberseguridad", "professional"),
  c("eCPTX", "INE", "ciberseguridad", "expert"),
  c("GIAC GMON", "GIAC", "ciberseguridad", "professional"),
  c("GIAC GRID", "GIAC", "ciberseguridad", "professional"),
  c("Palo Alto PCNSA", "Palo Alto", "ciberseguridad", "associate"),
  c("Check Point CCSA", "Check Point", "ciberseguridad", "associate"),
  c("Fortinet FCSS", "Fortinet", "ciberseguridad", "expert"),
  c("Fortinet FCA", "Fortinet", "ciberseguridad", "associate"),
  // IA / ML extras (todo lo de la lista 171-210)
  c("OpenAI API Developer", "OpenAI", "ia", "associate"),
  c("LangChain Developer", "LangChain", "ia", "associate"),
  c("Prompt Engineering Professional", "Varios", "ia", "associate"),
  c("Azure OpenAI Specialist", "Microsoft", "ia", "professional"),
  c("Hugging Face Certification", "Hugging Face", "ia", "associate"),
  c("Dataiku ML Engineer", "Dataiku", "ia", "associate"),
  c("IBM Data Science Professional", "IBM", "ia", "professional"),
  c("Deep Learning Specialist", "Varios", "ia", "professional"),
  c("Computer Vision Engineer", "Varios", "ia", "professional"),
  c("NLP Specialist", "Varios", "ia", "professional"),
  c("LLM Engineer", "Varios", "ia", "professional"),
  c("AI Security Engineer", "Varios", "ia", "professional"),
  c("AI Governance Professional", "Varios", "ia", "professional"),
  c("MLOps Engineer", "Varios", "ia", "professional"),
  c("AI Platform Engineer", "Varios", "ia", "professional"),
  c("AI Solutions Architect", "Varios", "ia", "expert"),
  c("Responsible AI Professional", "Varios", "ia", "professional"),
  c("NVIDIA AI Infrastructure", "NVIDIA", "ia", "professional"),
  c("Agentic AI Engineer", "Varios", "ia", "professional"),
  c("Multi-Agent Systems Engineer", "Varios", "ia", "professional"),
  c("Enterprise AI Architect", "Varios", "ia", "expert"),
  // DevOps extras
  c("Red Hat Ansible Automation", "Red Hat", "devops", "professional"),
  c("GitHub Actions Certification", "GitHub", "devops", "associate"),
  c("Jenkins Engineer", "CloudBees", "devops", "associate"),
  c("ArgoCD Certified", "CNCF", "devops", "associate"),
  c("Red Hat OpenShift Developer", "Red Hat", "devops", "professional"),
  c("DevOps Foundation", "DevOps Institute", "devops", "fundamentos"),
  c("FinOps Professional", "FinOps Foundation", "devops", "professional"),
  c("Pulumi Fundamentals", "Pulumi", "devops", "fundamentos"),
  c("Platform Engineering", "Varios", "devops", "professional"),
  c("Azure DevOps Engineer Expert", "Microsoft", "devops", "expert"),
  c("Infrastructure as Code Expert", "Varios", "devops", "professional"),
  c("CI/CD Engineer", "Varios", "devops", "associate"),
  c("Cloud Native Engineer", "Varios", "devops", "professional"),
  c("Container Security Specialist", "Varios", "devops", "professional"),
  c("Service Mesh (Istio) Specialist", "Varios", "devops", "professional"),
  c("GitOps Engineer", "Varios", "devops", "associate"),
  // Virtualización extras
  c("VMware VCDX", "VMware", "linux", "expert"),
  c("VMware vSAN Specialist", "VMware", "linux", "professional"),
  c("VMware Aria", "VMware", "linux", "professional"),
  c("Nutanix NCA", "Nutanix", "linux", "fundamentos"),
  c("Nutanix NCM", "Nutanix", "linux", "expert"),
  c("Citrix CCP-V", "Citrix", "linux", "professional"),
  c("Citrix CCE-V", "Citrix", "linux", "expert"),
  c("Hyper-V Administrator", "Microsoft", "linux", "associate"),
  c("Virtual Desktop Specialist", "Varios", "linux", "associate"),
  c("VMware Cloud Certified", "VMware", "cloud", "professional"),
  // Bases de datos / Data extras
  c("Oracle Database Professional", "Oracle", "ia", "professional"),
  c("Microsoft SQL Server DBA", "Microsoft", "ia", "associate"),
  c("MySQL DBA", "Oracle", "ia", "associate"),
  c("MongoDB Professional Developer", "MongoDB", "ia", "professional"),
  c("Snowflake SnowPro Advanced", "Snowflake", "ia", "professional"),
  c("Databricks Data Engineer Associate", "Databricks", "ia", "associate"),
  c("Databricks Data Engineer Professional", "Databricks", "ia", "professional"),
  c("Google BigQuery Engineer", "Google Cloud", "ia", "professional"),
  c("Data Warehouse Specialist", "Varios", "ia", "professional"),
  c("Tableau Desktop Specialist", "Tableau", "ia", "associate"),
  c("Qlik Sense Data Analyst", "Qlik", "ia", "associate"),
  // Gobierno / Gestión extras
  c("ITIL 4 Managing Professional", "PeopleCert", "grc", "professional"),
  c("PRINCE2 Practitioner", "PeopleCert", "grc", "professional"),
  c("AgilePM", "APMG", "grc", "associate"),
  c("Professional Scrum Product Owner", "Scrum.org", "grc", "associate"),
  c("Lean Six Sigma Black Belt", "IASSC", "grc", "expert"),
  c("COBIT Design & Implementation", "ISACA", "grc", "professional"),
  c("ISO 20000 Lead Implementer", "PECB", "grc", "professional"),
  c("GDPR Certified Professional", "Varios", "grc", "professional"),
  c("TOGAF Enterprise Architect", "The Open Group", "grc", "professional"),
];

const res = await fetch("http://127.0.0.1:4000/api/certifications/import", {
  method: "POST",
  headers: { "Content-Type": "application/json", "x-import-token": TOKEN },
  body: JSON.stringify({ items }),
});
console.log("Enviadas:", items.length, "->", JSON.stringify(await res.json()));
